name: aws lamda cd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Download files"
        uses: actions/checkout@v2

      - name: "Deploy into aws"
        uses: andarms/encrypt-aws-env-vars@v5.2
          id: encrypt
        with:
          aws-region: "sa-east-1"
          aws-cmk-arn: ${{ secrets.AWS_CMK_ARN_ID }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          config-file-location: config.json
      
      - name: Run build
        run: echo ${{ steps.encrypt.outputs.encrypted-file-location }}
